### PR TITLE
Dev env setup

### PR DESCRIPTION
**Pull request by Neketek**
Basic development environment configuration. I'm using docker-compose because it has some important user-friendly features which standalone docker doesn't have. Anyway, there is a shortlist of things I've done:
1. Dockerized the dev env.
1. Added several basic Makefile commands shortcuts.
1. Configured pytest and coverage.
1. Created minimal setup.py script which builds click cli demo inside a docker container.
1. Added small readme which explains how to launch the whole thing. 

In theory, this should be more than enough to start rewriting our bash scripts in python.

### CODE REVIEW

**Comment by roleyfoley** [comment]
codeontap-cli 

Confirmed that it’s not in pipy using the package search

**Comment by Neketek** [comment]
@koriaf @roleyfoley I don't have write access, so it's up to you to merge PRs.

**Comment by koriaf** [comment]
neither do I

**Comment by Neketek** [comment]
I changed a few things:
1. Now we have ```cot``` dir instead of ```src``` because apparently root dir name is an import name of our package. 
1. Added basic skeleton for commands. Unprefixed will go into command dir. Who knows maybe in future we'll rename them and they will match one of the prefixes. 
1. Fixed an import problem in wheel package. Imports must be relative or use root package name which in our case is ```cot```. 

It looks like the story is short but it took a while to figure out what was causing all of the troubles.

**Pull request merged**
